### ISSUE TITLE
New release of mix-ide 1.2.7 crashes in Macosx 10.11.2 - El capitain

### ISSUE THREAD

**Issue by sussegaduss** [ethereum/webthree-umbrella#560] opened 2016-06-09 03:06 UTC
I installed the version 1.2.7 of ethereum cpp and, as i tried to open the mix-ide, it crashes with the message: Mix Ide Quit Unexpectedly.

**Comment by SorenPeterson** [comment] 2016-06-09 04:17
I can also confirm this with OS X 10.11.5

**Comment by ktorn** [comment] 2016-06-09 08:53
Same here with v1.2.7 on Mac OS X 10.11.5

Crash log: https://gist.github.com/ktorn/3b863c618362dba13597da0550a6ccf1

**Comment by bobsummerwill** [comment] 2016-06-09 15:28
Hey guys!

So this is a known issue which we're working through right now.

Debug binaries don't hit the issue, so you can build Mix from source (http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/osx.html) and that will work.

I'll be flipping the Homebrew and DMG builds to Debug JUST for Mix as a workaround.

See https://github.com/ethereum/webthree-umbrella/issues/546.

The actual root cause is a horrible https://en.wikipedia.org/wiki/Heisenbug which we've been battling for a month or more :-(

See also https://gitter.im/ethereum/mix?at=57570ee9662b042b7e594571

**Comment by bobsummerwill** [comment] 2016-06-09 18:20
I'm going to close this, because I've added you all to the #546 workaround.

**Closed as completed by bobsummerwill** 2016-06-09 18:20 UTC
Labels: bug
