### ISSUE TITLE
boost::exception_detail::clone_impl<dev::ExternalFunctionFailure>

### ISSUE THREAD

**Issue by index932** [ethereum/webthree-umbrella#263] opened 2016-02-24 23:47 UTC
Hi Folks, I am getting this error and my rigs are down due to this. Tried all updates and nothing worked. repeatedly getting the same error. please advise.

[OPENCL]:Found suitable OpenCL device [Tahiti] with 3026190336 bytes of GPU memory
miner  15:44:23.789|ethminer  Getting work package...
miner  15:44:24.590|ethminer  Grabbing DAG for #1250db29…
miner  15:44:48.924|ethminer  Got work package:
  ℹ  15:44:48.924|ethminer  Loading full DAG of seedhash: #4b77c50b…
miner  15:44:48.924|ethminer    Header-hash: 1baebe161be41b9e85466218d14240244f5b78815f7528a3aeaee5712247fa0f
miner  15:44:48.924|ethminer    Seedhash: 1250db2965df18ca201a546442dab4fdea6f6ed1a13e86ed691dc897dcb9799c
miner  15:44:48.924|ethminer    Target: 00000000dbe6fecebdedd5beb573440e5a884d1b2fbf06fcce912adcb8d8422e
  ℹ  15:44:48.924|gpuminer0  workLoop 0 #00000000… #1250db29…
  ℹ  15:44:48.924|gpuminer0  Initialising miner...
miner  15:44:49.424|ethminer  Mining on PoWhash #1baebe16… : 0 H/s = 0 hashes / 0.5 s
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tahiti(OpenCL 1.2 AMD-APP (1729.3))
terminate called after throwing an instance of 'boost::exception_detail::clone_impldev::ExternalFunctionFailure'
  what():  std::exception
Aborted (core dumped)

**Comment by bobsummerwill** [comment] 2016-02-25 00:08
Is this latest log against the 1.1.4 release, @index932?
What is your OS and hardware, please?

As @chriseth said ... Please give some more information. Which version of ethminer do you use? Do you use it together with cpp-ethereum or go-ethereum? In both cases: Which version? Do you mine in a pool or do you solo mine?

The error says "core dumped" which means it created a file called core. Can you send that over to us?

**Comment by skabbo** [comment] 2016-02-25 03:44
I'm having this exact same error - oddly, ethminer was working for about 3 weeks to a month, then suddenly threw this error and terminated.  I did a completely fresh install of Ubuntu, reinstalled AMD drivers, cpp-ethereum, and webthree-umbrella, re-downloaded the DAG, and it failed with this exact same error.
Ubuntu 14.04 - AMD R9 290X - 4gb RAM (system and video) - ethminer ver 1.1.4

Full text after initializing miner:

[OPENCL]:Found suitable OpenCL device [Hawaii] with 3221225472 bytes of GPU memory
miner  22:38:07.493|ethminer  Getting work package...
miner  22:38:07.917|ethminer  Grabbing DAG for #1250db29…
miner  22:38:34.399|ethminer  Got work package:
miner  22:38:34.399|ethminer    Header-hash: 129734afe99df7365bf5f51974ec953ecbf078022cf276d72b32f1639817bc07
miner  22:38:34.399|ethminer    Seedhash: 1250db2965df18ca201a546442dab4fdea6f6ed1a13e86ed691dc897dcb9799c
miner  22:38:34.399|ethminer    Target: 0000000225c17d04dad2965cc5a02a23e254c0c3f75d9178046aeb27ce1ca574
  ℹ  22:38:34.399|gpuminer0  workLoop 0 #00000000… #1250db29…
  ℹ  22:38:34.399|gpuminer0  Initialising miner...
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Hawaii(OpenCL 1.2 AMD-APP (1800.8))
  ℹ  22:38:34.399|ethminer  Loading full DAG of seedhash: #4b77c50b…
miner  22:38:34.899|ethminer  Mining on PoWhash #129734af… : 0 H/s = 0 hashes / 0.5 s
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Mapping one big chunk.
miner  22:38:55.511|ethminer  Got work package:
miner  22:38:55.511|ethminer    Header-hash: ad2577a124f7bd3451d0beceb20dbf59becfbbe97545be9ca4083b255f18e684
miner  22:38:55.511|ethminer    Seedhash: 1250db2965df18ca201a546442dab4fdea6f6ed1a13e86ed691dc897dcb9799c
miner  22:38:55.511|ethminer    Target: 0000000225c17d04dad2965cc5a02a23e254c0c3f75d9178046aeb27ce1ca574
terminate called after throwing an instance of 'boost::exception_detail::clone_impldev::ExternalFunctionFailure'
  what():  std::exception
Aborted (core dumped)

**Comment by index932** [comment] 2016-02-25 04:52
I got the same config as skabbo except I got R9 280x.

Ubuntu 14.04 - AMD R9 280X - 4gb RAM (system and video) - ethminer ver 1.1.4

I use with cpp-ethereum. I mine on http://ethpool.org/

I will grab that core file and attach asap.

**Comment by bobsummerwill** [comment] 2016-02-25 06:25
Thanks, @index932!

**Comment by skabbo** [comment] 2016-02-25 11:51
Sorry to piggyback on this, but they do seem pretty identical.  Here's the core.cpp from mine.   It calls an include "boost/test/unit_test.hpp" which doesn't exist in any of the webthree subdirs, and then the terminate includes "boost::" - possibly related?
Grasping at straws, since this worked fine for much longer than it hasn't.
[core.cpp.zip](https://github.com/ethereum/webthree-umbrella/files/146428/core.cpp.zip)

**Comment by index932** [comment] 2016-02-25 16:45
Even after zipping the file, it is too large i think, it is not letting me attach here.

 86188032 Feb 25 08:39 core
 45967303 Feb 25 08:42 core.zip

**Comment by index932** [comment] 2016-02-25 16:51
Here we go, the good old dropbox: https://www.dropbox.com/s/1mxnh8par8mp3bx/core.zip?dl=0

**Comment by index932** [comment] 2016-03-02 05:32
Folks, any help on this is greatly appreciated. please advise.

**Comment by klhutchins1** [comment] 2016-03-02 06:17
I am getting the same error.
It was working fine for at least a few months and last time I tried about 2 weeks ago it was fine. Around Friday I started to get this:

> 'boost::exception_detail::clone_impldev::ExternalFunctionFailure'
>   what():  std::exception

It was working on Ubuntu 14.04. 

Since it stopped, I've tried rebuilding on both 14.04 and 15.10 
ADL_SDK8.zip and ADL_SDK9.zip
ethminer ver 1.1.3 and 1.1.4

not sure where to find the core dump to look through

**Comment by gcolvin** [comment] 2016-03-02 16:09
Is it possible to pinpoint just what changed when that caused it to stop working? No sooner than 7 days ago, it seems.

**Comment by skabbo** [comment] 2016-03-02 16:49
Looking at payout history, it appears I started getting this error on Feb
23rd.  It had worked consistently for the last month before that.

**Comment by chriseth** [comment] 2016-03-02 17:44
Hm, the failure seems to be related to allocating an new DAG. Can you see whether there is something strange in `~/.ethash`? Perhaps renaming or wiping it could help. Your disk is not full, is it?

**Comment by skabbo** [comment] 2016-03-02 17:56
Can't speak for index932 or klhutchins, but nothing unusual in ~./ethash.  I've wiped it clear and let it re-create the DAG, which it does successfully before crashing.  I have approx. 5gb free after creation of the DAG (running on a 16gb thumb drive - it was mining successfully with less free space than that for a while).

**Comment by klhutchins1** [comment] 2016-03-03 00:57
Originally I was on a 40GB drive, but while I was re-doing everything I threw a 300GB in there. 
Currently after re-creating the DAG I'm at 11.5 GB used and 267 GB free.

I am also running a R9 280X 3GB

**Comment by gcolvin** [comment] 2016-03-03 17:20
@skabbo did you change the code you were running on the 23rd, or did it just crap out on its own?

**Comment by index932** [comment] 2016-03-05 00:50
In my case, in all my 3 machines where I got this error, I did not change any code, they were running for months together without any issue and all of a sudden, they all crapped out. Later I started updating stuff and nothing helped, same error...

**Comment by bobsummerwill** [comment] 2016-03-05 00:54
Yikes.    Like it's hit a "bad block", or some edge case where it just cannot get past a particular point?

To be clear ... you are seeing this even with a completely fresh install, with all data cleared out too?    I'm asking this of @index932, @klhutchins1 and @skabbo.

If so, we have a very serious problem indeed.

**Comment by index932** [comment] 2016-03-05 01:00
@bobsummerwill, I am redoing one of my machines from scratch now. It is building DAG as I write this. I should know the results in few minutes....

**Comment by skabbo** [comment] 2016-03-05 01:21
Yes in my case - the problem recurred after installing Ubuntu 14.04 on a
fresh USB stick, re-compiling webthree-umbrella and rebuilding the DAG.

**Comment by index932** [comment] 2016-03-05 01:26
Got the same error... :(

**Comment by bobsummerwill** [comment] 2016-03-05 03:02
@klhutchins1 - What is your OS version, GPU etc, please?

**Comment by bobsummerwill** [comment] 2016-03-05 15:30
Adding @smartbitcoin, who has been looking at CPU mining, and might have some insight into the code as it applies to GPU mining as well.

**Comment by smartbitcoin** [comment] 2016-03-05 15:39
I don't have GPU in my office environment,  so I have no idea why GPU mining stuck there. After hit the libethcore,  cpu and gpu go different code branch,  they won't affect each other. but for DAG generation , it's all come from same libethash.

**Comment by klhutchins1** [comment] 2016-03-05 15:58
currently, it is:
Ubuntu 15.10
Intel Pentium 4 CPU 2.80GHz 
1GB RAM
300GB sata HD
ATI R9 280X - fglrx drivers
geth  1.4.0-unstable
ethminer version 1.2.0

I'm having trouble even running the benchmark

> :~$ ethminer -G -M
> [OPENCL]:Found suitable OpenCL device [Tahiti] with 3030384640 bytes of GPU memory
> Benchmarking on platform: { "platform": "AMD Accelerated Parallel Processing", "device": "Tahiti", "version": "OpenCL 1.2 AMD-APP (1800.8)" }
> Preparing DAG...
> Warming up...
>   ℹ  08:20:40.918|gpuminer0  workLoop 0 #00000000… #00000000…
>   ℹ  08:20:40.918|gpuminer0  Initialising miner...
> Trial 1... 0
> Trial 2... 0
> Trial 3... 0
> Trial 4... 0
> Trial 5... 0

It will either sit here or crash the computer (happened only once). I haven't been able to get it past this cleanly.

**Comment by ghost** [comment] 2016-03-05 18:19
If it's any help. I had .ethash linked to a different hdd from my sdd. This worked for months. Then got this error a few days ago. I removed the link and rebuild dag to the local sdd. Works find now. It might be permissions/access issue with .ethash

**Comment by bobsummerwill** [comment] 2016-03-05 18:23
Thanks for that suggestion, @etherninja!

**Comment by darkstar422** [comment] 2016-03-10 01:06
Hello,

I seem to be getting the same error. I would appreciate any help.

**Environment:**
OS: Ubuntu 15.10 i386 32bit
Ram: 6 GB
GPU: 2 x Nvidia GeForce Gt 710
Geth Version: 1.3.5
Ethminer Version: 1.2.0

I've got geth up and running in one console with no errors using the following command.
_mine1@node1:~$ geth --rpc console_

**Error I'm Getting**
I'm getting the following error while trying to run ethminer: 
![image](https://cloud.githubusercontent.com/assets/17754244/13656152/9667e17c-e621-11e5-907e-29ef250246ae.png)

**Comment by skabbo** [comment] 2016-03-10 04:08
Hey darkstar - thanks for the contribution.
I'm curious - since yours is the only one so far not running an AMD card, which gives us _some_ information to work with..  Is it possible this is related to 32 bit operating systems?  I'm running the 32 bit build of 14.04 (older processor), and **darkstar** is too.  What about the rest of us?  klhutchins1?  index932?  If everyone experiencing this is on Ubuntu 32bit that could narrow it way down.
Thanks!

**Comment by bobsummerwill** [comment] 2016-03-10 10:36
Something else you guys could try is looking at the @Genoil version of ethminer.

See http://github.com/Genoil/cpp-ethereum, which appears to be more popular than the "official" ethminer.

**Comment by bobsummerwill** [comment] 2016-03-10 10:38
@skabbo Good detective work!   If you are all on 32-bit systems, that might well be relevant in some way, because that is not really a use-case which gets any kind of love, either on eth or on geth.

The focus is always on 64-bit systems, because they are so prevalent now, for Desktops at least.   

Mobile, wearable and embedded are still dominated by 32-bit.   First few 64-bit SBCs just starting to appear.

**Comment by darkstar422** [comment] 2016-03-10 16:03
Thanks for the response. I'm just going to rebuild on a 64bit system. I'll let you know the outcome.

**Comment by index932** [comment] 2016-03-10 21:15
Okay. that could be the case. I am on 32 bit as well. Gonna redo the whole thing on a 64 bit and see how that goes (will take some time to chance the board and processor) but will do that and update the gang.!
Really appreciate all the input guys!

**Comment by bobsummerwill** [comment] 2016-03-10 22:16
Aha - thanks, @index932, @darkstar422.    Please do report back on how it goes.

Might make sense for us to put up a big disclaimer/banner in the Linux instructions warning about this.

**Comment by darkstar422** [comment] 2016-03-11 16:55
I rebuilt in 64bit and it is working fine now. Everything else is exactly the same.

**Comment by index932** [comment] 2016-03-11 19:39
@darkstar422 Great info. I am waiting on my 64 bit processor. I am sure that is going to work for me as well. Thanks again.

**Comment by darkstar422** [comment] 2016-03-12 01:56
Hi Bob,

When i rebuilt I made a new build guild with a friend of mine. Thought I would share.

http://mflukerngx.github.io/setup-guide/

**Comment by bobsummerwill** [comment] 2016-03-12 16:39
Fantastic, @darkstar422!
I've dragged you into the Homestead Guide gitter channel, because I think you could really help improve the Mining content we have there

**Comment by bobsummerwill** [comment] 2016-03-12 16:41
I've been adding "We only support 64-bit" disclaimers throughout our docs.ethereum.org content, and will close this issue now.    Thanks for your reports and help with working out that 32-bit was the root cause, guys.   Thanks!

**Closed as completed by bobsummerwill** 2016-03-12 16:41 UTC
Labels: bug, question

**Comment by riprowan** [comment] 2016-03-14 04:41
@darkstar422 thanks for your commentary - I'm setting up my system which happens to be almost identical to yours, this was a big help.
