### ISSUE TITLE
Aleth One / Aleth Zero / Mix crashing on Mac OS X Yosemite (10.10.5)

### ISSUE THREAD

**Issue by ivica7** [ethereum/webthree-umbrella#362] opened 2016-03-15 05:13 UTC
I installed the binaries from https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.2 on my Mac OS X Yosemite. All three applications crash with the same error.

The full AlethZero error reports is attached.

```
...
Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Application Specific Information:
/Applications/AlethOne.app/Contents/MacOS/../Frameworks/libdevcrypto.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdevcrypto.dylib              0x000000010db0ce9a CryptoPP::InvalidKeyLength::InvalidKeyLength(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) + 422
1   dyld                            0x00007fff61b2fd0b ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 265
2   dyld                            0x00007fff61b2fe98 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
...
Model: MacBookPro7,1, BootROM MBP71.0039.B0E, 2 processors, Intel Core 2 Duo, 2.4 GHz, 6 GB, SMC 1.62f7
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
```

**Comment by christianbm1** [comment] 2016-03-15 23:55
Same issue here.

**Comment by chriseth** [comment] 2016-04-18 21:33
Could you please try again with the latest version from today? Thanks!

**Comment by bobsummerwill** [comment] 2016-06-10 05:03
Closed as dupe of "The Heisenbug" - https://github.com/ethereum/webthree-umbrella/issues/565.   We can reopen if we later find there is anything unique here.

**Closed as completed by bobsummerwill** 2016-06-10 05:03 UTC
Labels: bug
