### ISSUE TITLE
Remove CryptoPP dependency

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#172] opened 2016-02-08 23:46 UTC
It seems to be necessary because of "some Windows build magic".

See https://github.com/ethereum/webthree-umbrella/issues/103

subtly is keen to get this done, and has offered to help.

**Comment by bobsummerwill** [comment] 2016-03-01 21:13
Hey @subtly.

Looking at my post-Homestead target diagram:
http://doublethinkco.github.io/webthree-umbrella-cross/images/target_dependency_graph.svg

Looking at CryptoPP and secp256k1 - are those effectively just alternative implementations which devcrypto sit on top of?    So this task would just involve removing those conditionals, and using secp256k1 unconditionally on all platforms?

What about the gmp dependency?   Is that a pretty lightweight dependency?   What are we using GMP for?   Is there overlap with boost?

More generally, I'm going to want to undo the lazy global dependencies which our build system has introduced onto json_spirit, boost, JsonCpp, pthreads and leveldb - and to readd those libraries exactly-and-only-as-required to each of our other modules.

CC @gcolvin and @chriseth.

**Comment by bobsummerwill** [comment] 2016-04-04 19:55
Dupe of #103.

**Closed as completed by bobsummerwill** 2016-04-04 19:55 UTC
Labels: enhancement
