### ISSUE TITLE
OS X - Binaries for El Capitan

### ISSUE THREAD

**Issue by chriseth** [ethereum/webthree-umbrella#185] opened 2016-02-09 15:14 UTC
We should provide binaries for MacOS El Capitan. This requires e.g. a jenkins worker on an El Capitan machine. We might ask the go team if we could use one of their machines just for the build.

**Comment by bobsummerwill** [comment] 2016-04-25 15:29
Dupe of https://github.com/ethereum/webthree-umbrella/issues/454

**Closed as completed by bobsummerwill** 2016-04-25 15:29 UTC
Labels: enhancement
