### ISSUE TITLE
Windows - Build problem on windows: boost_atomic

### ISSUE THREAD

**Issue by milyInzhoop** [ethereum/webthree-umbrella#235] opened 2016-02-17 11:55 UTC
Building ad described in wiki on Windows 8.1 with VS12 and Cmake 3+ I receive the following error in console:
"Could not find the following static Boot libraries: boost_atomic"

Attached the CmakeError file
[CMakeError.txt](https://github.com/ethereum/webthree-umbrella/files/134182/CMakeError.txt)

Please help me.

**Comment by bobsummerwill** [comment] 2016-02-18 01:09
Are you getting this error during the CMake generation itself, @milyInzhoop?
Also, I don't quite understand what the attached log file is.    Please could you explain in a little more detail the command-line you are running, and the output you see?   Step by step?   Thanks!

**Comment by milyInzhoop** [comment] 2016-02-18 10:42
I follow step-by-step this wiki: https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows
(with VS2013, Windows 8.1 64bit, cmake 3.5.0).
The problem occurs when I try to Generate solution with CMake with the follow:

### 

> cd C:\webthree-umbrella
> C:\webthree-umbrella> mkdir build
> C:\webthree-umbrella> cd build
> C:\webthree-umbrella\build> cmake -G "Visual Studio 12 2013 Win64" .. 

the attached file is the Cmake error report.

**Comment by milyInzhoop** [comment] 2016-02-18 10:50
Attached what diplayed on the console during cmake
[console.txt](https://github.com/ethereum/webthree-umbrella/files/136058/console.txt)

**Comment by bobsummerwill** [comment] 2016-02-18 16:08
Adding @LianaHus, who has also seen this issue.

I suspect that you don't have boost at all, and that atomic is just the first library which it hits.

You did run the `getstuff.bat` batch file, right?   I suspect that something went wrong there, because the failure you are reporting is pretty simple - missing files which should be there.

**Comment by bobsummerwill** [comment] 2016-02-18 16:09
Do you happen to have a log of that batch file running?   Or please could you generate one?

It is better to generate a gist.github.com and to link to that, rather than using attachments.   Thanks!

**Comment by winsvega** [comment] 2016-02-19 10:26
Don't use cmake 3.5.  I had the same issue. 
Cmake 3.4.x  works fine

**Comment by milyInzhoop** [comment] 2016-02-19 14:05
yes I ran the getstuff.bat! Here the console when I ran it again: https://gist.github.com/milyInzhoop/84b51e11605c602389c3
(sorry for the attachments, I did not know the Convention).

Now I will make a test with the 3.4.3 version of Cmake, 
I'll let you know.

**Comment by milyInzhoop** [comment] 2016-02-19 14:46
Great!! Fantastic! It's ok now! 
I can confirm that the problem due to the Cmake version.

**Comment by bobsummerwill** [comment] 2016-02-19 14:55
Thanks, @winsvega!

So they had a regression in CMake 3.5?   Or maybe a syntax change?  What do you think? 

That is UGLY.

**Comment by milyInzhoop** [comment] 2016-02-19 15:16
From a quick glance at the release note of 3.5 version ( https://cmake.org/cmake/help/v3.5/release/3.5.html ), it not seems to talk about syntax changes. But there are some changes in findBoost module.

**Comment by bobsummerwill** [comment] 2016-02-19 22:43
OK - original issue fixed, so closing this ticket.

Chasing a possible regression in CMake is now tracked as https://github.com/ethereum/webthree-umbrella/issues/249.

**Closed as completed by bobsummerwill** 2016-02-19 22:43 UTC
Labels: bug
