### ISSUE TITLE
doc instruction for building solidity

### ISSUE THREAD

**Issue by winsvega** [ethereum/webthree-umbrella#707] opened 2016-08-25 08:14 UTC
this page lack of instruction on how to build solidity on windows. (it is similar for cpp-ethereum)

http://solidity.readthedocs.io/en/latest/installing-solidity.html#building-from-source

**Comment by bobsummerwill** [comment] 2016-08-25 23:11
Dupe of https://github.com/ethereum/solidity/pull/946.

Please don't open any new issues in `webthree-umbrella` anymore, @winsvega.

There can just go directly in `cpp-ethereum`, `solidity`, `evmjit`, `remix`, etc.

I will slew the ones still here into `cpp-ethereum` shortly.

**Closed as completed by bobsummerwill** 2016-08-25 23:11 UTC
