### ISSUE TITLE
Unable to build solution on Windows 7

### ISSUE THREAD

**Issue by trickybluefox** [ethereum/webthree-umbrella#81] opened 2015-10-25 16:26 UTC
I have followed the installation Wiki and have the project/solution ready for build.  When I try to build the entire solution (approx 61 projects all together) I receive more than 30K errors.  I built the solution with Cmake using Visual Studio Express 2012. Should I just try and build each project individually or am I missing key components here?

**Comment by LefterisJP** [comment] 2015-10-25 17:28
Cmake version? Also as the [wiki](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Windows) states please make sure to [download Visual Studio 2013 express](https://www.visualstudio.com/downloads/download-visual-studio-vs#) as we don't support 2012.

Please just read the wiki carefully and follow its instructions. If you still have errors, then reopen this issue and post them here or in a gist so that we can help you.

**Comment by trickybluefox** [comment] 2015-10-26 15:20
Boy is my face red.  Thanks for the help I usually pride myself on attention to detail but I dropped the ball here.  Appreciate the response. 

```
 On Sunday, October 25, 2015 11:28 AM, Lefteris Karapetsas <notifications@github.com> wrote:
```

 Cmake version? Also as the wiki states please make sure to download Visual Studio 2013 express as we don't support 2012.Please just read the wiki carefully and follow its instructions. If you still have errors, then reopen this issue and post them here or in a gist so that we can help you.—

**Comment by trickybluefox** [comment] 2015-10-28 00:47
I started from scratch and downloaded the latest repository again and followed the instructions from the wiki.  I successfully cloned the repository and ran getstuff.bat.  When I build the solution I get about 99 errors stating:

error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in JIT.obj  C:\webthree-umbrella\build\libethereum\evmjit\libevmjit\LLVMCore.lib(MetadataTracking.obj)  evmjit

and then about 800 errors stating:

error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in JIT.obj  C:\webthree-umbrella\build\libethereum\evmjit\libevmjit\LLVMCore.lib(MetadataTracking.obj)  evmjit

for a total of 909 errors I found a work around that resolves the first issue where you just hard code the value of the iterator debug level to 0. But I have tried changing the "Runtime library" setting to every available value, /MD /MDd /MTd /MT, and still receive the same errors + or - a few dozen errors. 

Cmake Version: 3.4.0-rc2
Visual Studio 2013 (when i downloaded it it said Visual studio community 2013 with update 5 RTM)

**Comment by arkpar** [comment] 2015-10-28 12:37
I don't think we support debug builds with `EVMJIT=1`
Either run `cmake -DEVMJIT=0` or build in release.
@chfast could you confirm that?

**Comment by chfast** [comment] 2015-10-28 12:44
The problem is that getstaff.bat contains only release version of LLVM. You can only build Release version of ethereum VS solution.

If you need something other than that, you would need to build LLVM libraries yourself.

**Comment by tidymonkey81** [comment] 2015-11-14 18:41
Win10 64bit.

same number and type of errors. i also thought i switched to release after git clone too. i'm going to double check ~~but what does -DEVMJIT=0 flag do?~~ attempting now

Error   2   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in JIT.obj  D:\code\src\webthree-umbrella\build\libethereum\evmjit\libevmjit\LLVMCore.lib(MetadataTracking.obj) evmjit

Error   3   error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in JIT.obj  D:\code\src\webthree-umbrella\build\libethereum\evmjit\libevmjit\LLVMCore.lib(MetadataTracking.obj) evmjit

Fixed with -DEVMJIT=0. Shouldn't that be in the wiki?

**Comment by tidymonkey81** [comment] 2015-11-14 19:02
cmake version 3.4.0-rc3
Visual Studio 2013
Windows 7 SDK

not sure how to set -DEVMJIT=0

**Comment by chfast** [comment] 2015-11-14 23:14
Another solution is building Release version instead of Debug one.

**Comment by bobsummerwill** [comment] 2016-01-15 05:21
Greetings all.

I'm going to close this long ticket, because from what I can see the issue is rather simpler - Release config works.   Debug config is broken.

Which I hit myself and logged in https://github.com/ethereum/webthree-umbrella/issues/123.

**Closed as completed by bobsummerwill** 2016-01-15 05:21 UTC
