### ISSUE TITLE
OSX: AlethOne initial window was not sized correctly on first open

### ISSUE THREAD

**Issue by l0c0luke** [ethereum/webthree-umbrella#4] opened 2015-09-15 18:31 UTC
too short, needed to drag the little window down to see all the text.

**Comment by chriseth** [comment] 2016-02-23 17:22
I guess this is also about the master password dialog, so this should be a duplicate of https://github.com/ethereum/webthree-umbrella/issues/178

**Closed as completed by chriseth** 2016-02-23 17:22 UTC
Labels: bug
