### ISSUE TITLE
Error: INVALID_PARAMS: causes Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by colm** [ethereum/webthree-umbrella#101] opened 2015-12-13 17:05 UTC
Playing with eth trying to do the greeter tutorial in different ways. 

Set up my private test net with:

eth --private --networkid=9195335 --genesis-json ~/test/genesis.json --db-path ~/.ethereum_experiment --no-discovery --hermit --no-bootstrap -i

compile code, try to create contract and It gives INVALID_PARAMS this is probably my mistake. But then it immediately seg faults. I assume it should fail gracefully. 

[greet.txt](https://github.com/ethereum/webthree-umbrella/files/60525/greet.txt)

Code attached. 

Thanks, 
Colm

**Comment by chriseth** [comment] 2016-01-18 08:33
I think that the "INVALID_PARAMS" is due to JsonRPC being forced to be sychronous. This will hopefully be fixed in the future. The crash should be fixed more urgently.

**Comment by chriseth** [comment] 2016-02-19 18:32
I was able to reproduce the INVALID_PARAMS error: You have to change `contract.code` to `contract.greeter.code`. I was not able to reproduce the crash, it is likely already fixed.

**Closed as completed by chriseth** 2016-02-19 18:32 UTC
Labels: bug
