### ISSUE TITLE
brew install fails to build

### ISSUE THREAD

**Issue by jesuscript** [ethereum/webthree-umbrella#208] opened 2016-02-13 20:38 UTC
Running `brew install` (or reinstall) fails with the following output (with or without the --devel option)

El Capitan, 10.11.3

```
$ brew reinstall cpp-ethereum --devel
==> Reinstalling ethereum/ethereum/cpp-ethereum
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/
==> make
Last 15 lines from /Users/megatv/Library/Logs/Homebrew/cpp-ethereum/02.make:
/usr/local/Library/ENV/4.3/clang++  -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -O3 -DNDEBUG -DETH_RELEASE -dynamiclib -Wl,-headerpad_max_install_names  -o libethash.dylib -install_name /tmp/cpp-ethereum20160213-34034-1j47hi/libethereum/libethash/libethash.dylib CMakeFiles/ethash.dir/io.c.o CMakeFiles/ethash.dir/internal.c.o CMakeFiles/ethash.dir/io_posix.c.o CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o /usr/local/lib/libcryptopp.a 
[  5%] Linking C shared library libscrypt.dylib
cd /tmp/cpp-ethereum20160213-34034-1j47hi/webthree-helpers/utils/libscrypt && /usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_link_script CMakeFiles/scrypt.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang  -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names  -o libscrypt.dylib -install_name /tmp/cpp-ethereum20160213-34034-1j47hi/webthree-helpers/utils/libscrypt/libscrypt.dylib CMakeFiles/scrypt.dir/b64.c.o CMakeFiles/scrypt.dir/crypto-mcf.c.o CMakeFiles/scrypt.dir/crypto-scrypt-saltgen.c.o CMakeFiles/scrypt.dir/crypto_scrypt-check.c.o CMakeFiles/scrypt.dir/crypto_scrypt-hash.c.o CMakeFiles/scrypt.dir/crypto_scrypt-hexconvert.c.o CMakeFiles/scrypt.dir/crypto_scrypt-nosse.c.o CMakeFiles/scrypt.dir/sha256.c.o CMakeFiles/scrypt.dir/slowequals.c.o 
[  5%] Built target ethash
[  5%] Built target scrypt
[  5%] Linking C static library libsecp256k1.a
cd /tmp/cpp-ethereum20160213-34034-1j47hi/webthree-helpers/utils/secp256k1 && /usr/local/Cellar/cmake/3.4.3/bin/cmake -P CMakeFiles/secp256k1.dir/cmake_clean_target.cmake
cd /tmp/cpp-ethereum20160213-34034-1j47hi/webthree-helpers/utils/secp256k1 && /usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_link_script CMakeFiles/secp256k1.dir/link.txt --verbose=1
/usr/bin/ar qc libsecp256k1.a  CMakeFiles/secp256k1.dir/secp256k1.c.o
/usr/bin/ranlib libsecp256k1.a
[  5%] Built target secp256k1
[  5%] Built target ethereum_BuildInfo.h
[  5%] Built target cpp-ethereum_BuildInfo.h
make: *** [all] Error 2
```

**Comment by bobsummerwill** [comment] 2016-02-14 04:52
Hey @jesuscript!
The error message is truncated.   Please could you copy /Users/megatv/Library/Logs/Homebrew/cpp-ethereum/02.make into a gist or pastie?  Thanks!

**Comment by bobsummerwill** [comment] 2016-02-14 18:51
Closing as a dupe of #213

**Closed as completed by bobsummerwill** 2016-02-14 18:51 UTC
Labels: bug

**Comment by jesuscript** [comment] 2016-02-15 11:36
oh, didn't realise i opened this twice... sorry

**Comment by bobsummerwill** [comment] 2016-02-15 15:34
np!
