### ISSUE TITLE
Hashrate down to 0 

### ISSUE THREAD

**Issue by awrelll** [ethereum/webthree-umbrella#570] opened 2016-06-10 14:00 UTC
Since I updated to 1.2.7 ethminer stopped delivering work. No clue how to downgrade...
miner  16:59:00.201|ethminer  Mining on PoWhash #c3110e7e… : 0 H/s = 0 hashes / 0.502 s
miner  16:59:00.704|ethminer  Mining on PoWhash #c3110e7e… : 0 H/s = 0 hashes / 0.502 s
miner  16:59:01.206|ethminer  Mining on PoWhash #c3110e7e… : 0 H/s = 0 hashes / 0.502 s
miner  16:59:01.708|ethminer  Mining on PoWhash #c3110e7e… : 0 H/s = 0 hashes / 0.502 s

**Comment by bobsummerwill** [comment] 2016-06-10 15:09
Hey @awrelll,
Closing as a dupe of https://github.com/ethereum/webthree-umbrella/issues/558.
Fix brewing right now at https://github.com/ethereum/libethereum/pull/281.

" No clue how to downgrade" ... is that because you're on OS X and getting your binary via Homebrew?

**Closed as completed by bobsummerwill** 2016-06-10 15:09 UTC
Labels: bug

**Comment by awrelll** [comment] 2016-06-10 15:12
I'm running Ubuntu 15. Thanks !

**Comment by bobsummerwill** [comment] 2016-06-10 15:14
I see https://gitter.im/ethereum/cpp-ethereum?at=575a9bfb064b9e7266f13c00 now.    Will talk there.

**Comment by bobsummerwill** [comment] 2016-06-11 02:12
Here you go - thanks!
https://twitter.com/BobSummerwill/status/741450414290149376

If you aren't getting a 1.2.8 from the PPA, please do let us know.   We have had issues with Launchpad before, and can get silent failures for the PPA to update, which we only discover when people say "Err - where is the new build?"

**Comment by renlord** [comment] 2016-06-13 07:22
The 1.2.8 PPA still ships with ethminer 1.2.7

ethminer version 1.2.7
Build: Linux/g++/Interpreter/RelWithDebInfo

**Comment by siemien** [comment] 2016-06-13 15:53
Same problem here, please Update the repositories

**Comment by bobsummerwill** [comment] 2016-06-14 00:47
Gah!    Yes, my bad.    I need to fix this and will try to do a fresh round of builds tonight.

See https://github.com/ethereum/webthree-umbrella/issues/583.

**Comment by bobsummerwill** [comment] 2016-06-14 00:48
If you need working miners now, please build-from-source on develop.    That will work.
