### ISSUE TITLE
No hashrate logs with Ethminer

### ISSUE THREAD

**Issue by jmiehau** [ethereum/webthree-umbrella#88] opened 2015-11-22 22:31 UTC
I did a reinstall of fresh Ubuntu 15.10, I have been used since genesis Geth + Ethminer. It seems with the current ethminer that I am not able to watch the hashrate logs:
https://gist.github.com/jmiehau/4ab14198b7b247c8e4d1

The GPU gets hot but I cannot track the proper mining like before.

**Comment by jmiehau** [comment] 2015-11-22 22:48
I tried to work for a pool with the same ethminer and it submits accepted shares https://gist.github.com/jmiehau/018bad0f356b86b6fd04

**Comment by tcoulter** [comment] 2015-12-04 19:16
I'm seeing this as well. Even when I set `verbosity` to 9.

https://gist.github.com/tcoulter/b29b4517723d4c059e2b

**Comment by sterkey25** [comment] 2016-02-17 16:32
just wondering if you ever found a solution for this yourselves?

**Comment by tcoulter** [comment] 2016-02-17 16:37
@sterkey25 I did actually. I created a new ticket about it here, and it requires adding a single line to the code in a specific spot. It looks like the devs added that line back in, but if you don't want to wait for them to release it you could add it in yourself and compile from source. Ticket is here. Check out the linked code sample: https://github.com/ethereum/webthree-umbrella/issues/200

**Comment by tcoulter** [comment] 2016-02-17 16:37
This one can probably be closed as it's a dupe of #200

**Comment by sterkey25** [comment] 2016-02-17 17:34
It seems that that line is already included now. I went to add it and it was already there so the problem may be something else, I am on Ubuntu 15.10 so im not sure if its that that is messing with it.

**Comment by chriseth** [comment] 2016-02-17 18:55
Please try again with version 1.1.4, should be fixed (together with #200). If not, please re-open.

**Closed as completed by chriseth** 2016-02-17 18:55 UTC
Labels: enhancement
